-- Create transactions table for logging all TAMA operations
CREATE TABLE IF NOT EXISTS public.transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id text NOT NULL,
    username text,
    type text NOT NULL,
    amount numeric NOT NULL,
    balance_before numeric,
    balance_after numeric,
    metadata jsonb
);

-- Add indexes for faster queries
CREATE INDEX IF NOT EXISTS transactions_user_id_idx ON public.transactions (user_id);
CREATE INDEX IF NOT EXISTS transactions_type_idx ON public.transactions (type);
CREATE INDEX IF NOT EXISTS transactions_created_at_idx ON public.transactions (created_at DESC);
CREATE INDEX IF NOT EXISTS transactions_username_idx ON public.transactions (username);

-- Enable Row Level Security (RLS)
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- Allow read access for all users
CREATE POLICY "Enable read access for all users" ON public.transactions
    FOR SELECT USING (true);

-- Allow insert for authenticated users (anon role can insert via API key)
CREATE POLICY "Enable insert for all users" ON public.transactions
    FOR INSERT WITH CHECK (true);

-- Grant permissions to anon role
GRANT ALL ON TABLE public.transactions TO anon;
GRANT USAGE, SELECT ON SEQUENCE public.transactions_id_seq TO anon;

